name: Tests

on:
  #  TODO: remove
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    cancel-timeout-minutes: 20
    strategy:
      matrix:
        rust_version:
          - stable
          - "1.74.0" # MSRV
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust_version }}
      - name: Add rustfmt
        run: rustup component add rustfmt
      - name: Add clippy
        run: rustup component add clippy
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ runner.os }}-cargo
          workspaces: >
            lsm-tree -> target
            lsm-tree/examples/kv -> target
      - name: Build
        run: cargo build -v
        working-directory: lsm-tree
      - name: Format
        run: cargo fmt --all -- --check
        working-directory: lsm-tree
      - name: Clippy
        run: cargo clippy
        working-directory: lsm-tree
      - name: Run tests
        run: cargo test -v -- --nocapture
        working-directory: lsm-tree
        env:
          RUST_LOG: debug
      - name: Build & test LSM examples
        run: node compile_examples.mjs
        working-directory: lsm-tree
  cross:
    cancel-timeout-minutes: 20
    name: cross
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          # - aarch64-linux-android
          - aarch64-unknown-linux-musl
          # - i686-linux-android
          # - x86_64-linux-android
          - i686-unknown-linux-gnu
          - powerpc64-unknown-linux-gnu
          #- mips64-unknown-linux-gnuabi64
          - riscv64gc-unknown-linux-gnu
          #- x86_64-apple-darwin
          #- aarch64-apple-darwin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cross build --target ${{ matrix.target }}
        run: |
          cargo install cross
          cross build --target ${{ matrix.target }}
